spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:45.76.146.204}:3306/ekyc
    username: ${DB_USERNAME:superadmin}
    password: ${DB_PASSWORD:cYN2U_fRKT3rT1Qy}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL:none}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
    open-in-view: true
server:
  port: 8300
logging:
  level:
    org:
      apache:
        http: debug
    httpclient:
      wire: debug
  file:
    path: ./log
vida:
  oauth2:
    client:
      grantType: ${VIDA_OAUTH2_GRANT_TYPE:client_credentials}
      clientId: ${VIDA_OAUTH2_CLIENT_ID:partner-pcs}
      clientSecret: ${VIDA_OAUTH2_CLIENT_SECRET:87eecd71-efa6-4411-a1b4-948798ee3ccb}
      accessTokenUri: https://${VIDA_OAUTH2_URL:qa-sso.vida.id/auth/realms/vida/protocol/openid-connect/token}
      scope: ${VIDA_OAUTH2_SCOPE:roles}
  properties:
    ocrUrl: https://${VIDA_OCR_URL:services-sandbox.vida.id/verify/v1/ktp/ocr}
    livenessUrl: https://${VIDA_LIVENESS_URL:none}
    faceMatchUrl: https://${VIDA_FACEMATCH_URL:services-sandbox.vida.id/verify/v1/face/match}
    demogLiteUrl: https://${VIDA_DEMOG_LITE_URL:services-sandbox.vida.id/verify/v1/demog-lite}
    statusTransactionUrl: https://${VIDA_TRANSACTION_STATUS_URL:services-sandbox.vida.id/verify/v1/transaction/}
    faceThreshold: ${VIDA_FACE_THRESHOLD:3.0}
    demogThreshold: ${VIDA_DEMOG_THRESHOLD:1.0}
asliri:
  properties:
    ocrUrl: https://${ASLIRI_OCR_URL:api.asliri.id:8443/pcs_poc/ocr_extra}
    livenessUrl: https://${ASLIRI_LIVENESS_URL:none}
    faceMatchUrl: https://${ASLIRI_FACEMATCH_URL:api.asliri.id:8443/pcs_poc/verify_profesional}
    demogUrl: https://${ASLIRI_DEMOG_URL:api.asliri.id:8443/pcs_poc/verify_basic}
    extraTaxUrl: https://${ASLIRI_EXTRA_TAX_URL:api.asliri.id:8443/pcs_poc/verify_tax_extra}
    faceThreshold: ${ASLIRI_FACE_THRESHOLD:7.0}
    token: ${ASLIRI_TOKEN:OWIwNmFjOGYtYzZiOC00NGI1LTkwNzEtZWQ1OWVlZDk0YTRm}
ekyc:
  vendor:
    vida: ${EKYC_VENDOR_VIDA:1}
    vj: ${EKYC_VENDOR_VJ:2}
    asliRi: ${EKYC_VENDOR_ASLIRI:3}
    simulation: ${EKYC_VENDOR_SIMULATION:999}
  service:
    ocr: ${EKYC_SERVICE_OCR:1}
    liveness: ${EKYC_SERVICE_LIVENESS:2}
    faceMatch: ${EKYC_SERVICE_FACEMATCH:3}
    demog: ${EKYC_SERVICE_DEMOG:4}
    extraTax: ${EKYC_SERVICE_EXTRA_TAX:5}